<a href="https://colab.research.google.com/github/kusasyu36/ai-roadmap-2025/blob/main/week01_python_basics/nb_day5_modules.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import math# importは大抵セルの一番上に記述します
print(math.sqrt(2)) # sqrt は平方根を計算する関数
print(math.pi) # πの値
print(math.sin(math.pi/4)) # sin関数
print(math.cos(0)) # cos関数
print(math.log(32,2)) # 2を底とする32の対数（texで記述すると、$\log_2 32$）

1.4142135623730951
3.141592653589793
0.7071067811865475
1.0
5.0


In [2]:
from math import sqrt
print(sqrt(2)) # sqrt は平方根を計算する関数
from math import pi
print(pi) # πの値
from math import sin
print(sin(math.pi/4)) # sin関数
from math import cos
print(cos(0)) # cos関数
from math import log
print(log(32,2)) # 2を底とする32の対数（texで記述すると、$\log_2 32$）

1.4142135623730951
3.141592653589793
0.7071067811865475
1.0
5.0


In [3]:
from math import *

In [4]:
from math import *
print(factorial(5)) # 5 の階乗 # import mathを使う場合、math.factorial(5)
print(floor(2.31)) # 2.31以下の最大の整数  # import mathを使う場合、math.floor(2.31)
print(e) # ネイピア数 # import mathを使う場合、math.e

120
2
2.718281828459045


ただしこの方法は推奨されていません。理由は読み込んだモジュール内の未知の名前とプログラム内の名前が衝突する可能性があるためです。

#as

モジュール名が長すぎるなどの理由から別の名前としたい場合は、as を利用する方法もあります。 たとえば、5-3において学習するNumPyというライブラリは numpy モジュールとして提供されていますが、 次のように、 numpy を np という略称で使うことがあります。

In [5]:
import numpy
print(numpy.ones((3, 5))) # 3×5の行列を表示
import numpy as np
print(np.ones((3, 5))) # np という短い名称で同じ関数を利用する

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


個々の関数ごとに別の名前を付けることもできます。


In [6]:

import math
print(math.factorial(5)) # 階乗を求める関数factorial # 5の階乗
from math import factorial as fact # fact という名前でmath.factorialを使用したい
print(fact(5))

120
120


In [7]:
from math import sqrt, sin, pi
print(sqrt(2))
print(sin(pi))

1.4142135623730951
1.2246467991473532e-16


#モジュールファイル

本授業で扱ってきたノートブックファイル（拡張子 .ipynb）は、コードセル（Codeセル）にPythonソースコード、Markdownセルに文書を持ち、内部的に出力結果も保存しています。 一方、モジュールファイル（拡張子 .py）は、Pythonソースコードのみを含んだファイルです。

モジュールファイルを作るときには、Jupyter Notebook におけるコードセルの内容のみをファイルに記述することになります。

モジュールファイルの文字コードはUTF-8であることが公式に推奨されています。 原則としてUTF-8でエンコードして保存してください。



#ノートブックファイルをモジュールファイルに変換する

本授業で利用しているノートブックファイルを .py としてセーブするには、 「ファイル」メニューの「.py をダウンロード」項目を選択します。

そうすると、コードセルだけがプログラム行として有効になり、その他の行はコメントアウトされたモジュールファイルがダウンロードできます。 ダウンロード先はブラウザによって定まりますが、ダウンロードフォルダになることが一般的でしょう。

この方法では、全てのコードセルの内容を一度に実行するプログラムとして保存されます。 ノートブックのようにセル単位の実行するわけではないことに注意する必要があります。

#モジュールファイルをアップロードする

次に、ダウンロードしたモジュールファイルをColaboratoryで使うには、 Colaboratoryの実行環境の中のファイルシステムのカレントディレクトリに モジュールファイルをアップロードする必要があります。 このためには、以下のセルを実行してください。



In [8]:
import sys
if 'google.colab' in sys.modules:
    from google.colab import files
    uploaded = files.upload() # Upload to the current directory


KeyboardInterrupt: 

#自作モジュールの使い方

モジュールで定義されている関数を利用するには、import を用いて import モジュール名 と書きます。 モジュール名は、モジュールファイル名から拡張子 .py を除いたものです。

すると、モジュールで定義されている関数は モジュール名.関数名 によって参照できます。

次の関数が記述された factorial.py というモジュールを読み込む場合を説明します。 ただし、読み込み元と同じディレクトリに factorial.py が存在すると仮定します。

factorial.py:

In [9]:
import sys
if 'google.colab' in sys.modules:
    from google.colab import files
    uploaded = files.upload() # Upload to the current directory


Saving factorial_py.py to factorial_py.py


In [10]:
import factorial_py


In [11]:
factorial_py.fact(6)

720

#5-3. NumPyライブラリ

NumPyについて説明します。

NumPyとは、多次元配列を効率的に扱うライブラリです。 Pythonの標準ライブラリではありませんが、科学技術計算や機械学習など、ベクトルや行列の演算が多用される分野では、事実上の標準ライブラリとしての地位を確立しています。

NumPyを用いるには、まず、numpy モジュールをインポートする必要があります。 慣習として、np と別名をつけて利用されます。


NumPyでは、Python標準の数値やリストの代わりに、特別な数値や配列を用いることで、格段に効率的な配列演算を実現します。 以下では、配列の基本的な操作や機能を説明します。

#配列の構築

配列とは、特定の型の値の並びです。 numpy.array() 関数で構築できます。 このとき、配列の要素はPython標準のリストやタプルで指定します。 どちらを用いて作成しても全く同じ配列を作成できます。



In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [5]:
b = np.array((1, 2, 3))
print(b)

[1 2 3]


print の結果はリストと似ていますが、要素が , ではなく空白で区切られているに注意してください。 print ではなく、式の評価結果の場合、より違いが明示されます。

In [6]:
a

array([1, 2, 3])

In [7]:
b

array([1, 2, 3])

In [8]:
type(a)

numpy.ndarray

#要素型

配列の要素を構成する値には幾つかの型がありますが、次の4つの型を知っていればとりあえずは十分です。

型名

説明

numpy.int32

整数（32-bit）を表す型

numpy.float64

実数（64-bit）を表す型

numpy.complex128

複素数（64-bit実数の組）を表す型

numpy.bool_

真理値を表す型

配列は、リストと異なり、型の異なる要素を混在させることはできません。

array() の dtype 引数に、要素型を表すオブジェクトや文字列値を与えることで、指定された要素型の配列を構築できます。



In [13]:
print(np.array([-1, 0, 1], dtype=np.int32))
print(np.array([-1, 0, 1], dtype=np.float64))
print(np.array([-1,0,1], dtype=np.complex128))
print(np.array([-1,0,1], dtype=np.bool_))


[-1  0  1]
[-1.  0.  1.]
[-1.+0.j  0.+0.j  1.+0.j]
[ True False  True]


In [14]:
print(np.array([[1,2], [3,4]]))

[[1 2]
 [3 4]]


In [18]:
print(np.array([[[1,2], [3,4]], [[5,6],[7,8]]]))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
a1 = np.array([0,1,2,3,4,5])
a2 = a1.reshape(2,3)
a2

array([[0, 1, 2],
       [3, 4, 5]])

In [21]:
a1.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

ここで、reshape() を適用する前後の配列（ここでは a1 と a2）は、内部的にデータを共有していることに注意してください。 つまり、a1 の要素を更新すると、a2 にも影響を及ぼします。

In [22]:
a1[1]

np.int64(1)

In [23]:
a1[1] = 6
a1

array([0, 6, 2, 3, 4, 5])

In [24]:
a2

array([[0, 6, 2],
       [3, 4, 5]])

ravel() メソッドを使うと、多次元配列を1次元配列に戻すことができます。



In [25]:
a = np.array([0,1,2,3,4,5]).reshape(2,3)

In [26]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
a.ravel()

array([0, 1, 2, 3, 4, 5])

In [28]:
 a.dtype

dtype('int64')

In [29]:
a.shape

(2, 3)

In [30]:
a.ndim

2

In [31]:
a.size

6

In [32]:
a.flat

In [33]:
a.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [36]:
import itertools

In [38]:
counter = itertools.count(1)

for i, x in enumerate(counter):
  if i >= 15:
    break
  print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


In [39]:
import itertools

s = "eat"  # 例：3文字
perms = itertools.permutations(s)  # ('e','a','t'), ('e','t','a'), ...
print(perms)
anagrams = [''.join(p) for p in perms]
print(anagrams)  # ['eat', 'eta', 'aet', 'ate', 'tea', 'tae']

['eat', 'eta', 'aet', 'ate', 'tea', 'tae']


In [42]:
s = "kusasyu"
perms = itertools.permutations(s)
print(perms)
anagrams = [''.join(p) for p in perms]
print(anagrams)

['kusasyu', 'kusasuy', 'kusaysu', 'kusayus', 'kusausy', 'kusauys', 'kussayu', 'kussauy', 'kussyau', 'kussyua', 'kussuay', 'kussuya', 'kusyasu', 'kusyaus', 'kusysau', 'kusysua', 'kusyuas', 'kusyusa', 'kusuasy', 'kusuays', 'kususay', 'kususya', 'kusuyas', 'kusuysa', 'kuassyu', 'kuassuy', 'kuasysu', 'kuasyus', 'kuasusy', 'kuasuys', 'kuassyu', 'kuassuy', 'kuasysu', 'kuasyus', 'kuasusy', 'kuasuys', 'kuayssu', 'kuaysus', 'kuayssu', 'kuaysus', 'kuayuss', 'kuayuss', 'kuaussy', 'kuausys', 'kuaussy', 'kuausys', 'kuauyss', 'kuauyss', 'kussayu', 'kussauy', 'kussyau', 'kussyua', 'kussuay', 'kussuya', 'kusasyu', 'kusasuy', 'kusaysu', 'kusayus', 'kusausy', 'kusauys', 'kusysau', 'kusysua', 'kusyasu', 'kusyaus', 'kusyusa', 'kusyuas', 'kususay', 'kususya', 'kusuasy', 'kusuays', 'kusuysa', 'kusuyas', 'kuysasu', 'kuysaus', 'kuyssau', 'kuyssua', 'kuysuas', 'kuysusa', 'kuyassu', 'kuyasus', 'kuyassu', 'kuyasus', 'kuyauss', 'kuyauss', 'kuyssau', 'kuyssua', 'kuysasu', 'kuysaus', 'kuysusa', 'kuysuas', 'kuyusas'